config/routes.rb
Rails.application.routes.draw do

  get 'pages/lizards/:number', to: 'pages#lizards', as: 'lizards', number: /\d+/

  get 'pages', to: 'pages#home', as: 'home'

  get 'pages/about_us', to: 'pages#about_us', as: 'about'

  get 'products', to: 'products#index', as: 'index'

  get 'products/:id', to: 'products#show', as: 'product', id: /\d+/

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def lizards
    @lizards = params[:number].to_i
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order(:name)
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/common/_header.html.erb
<header>
  <nav>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Products', index_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'common/header' %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About page</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

app/views/pages/about_us.html.erb
<h2>About page</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

app/views/pages/home.html.erb
<h2>Home page</h2>
<p>Nam dignissim quam a finibus venenatis.</p>
<ol>
  <li><%= link_to '12 Lizards', lizards_path(22) %></li>
  <li><%= link_to '444 Lizards', lizards_path(444) %></li>
  <li><%= link_to '9672 Lizards', lizards_path(9672)%></li>
</ol>

app/views/pages/lizards.html.erb
<% @lizards.times do |lizard| %>
<p><%= image_tag 'lizard.png' %></p>
<% end %>

app/views/products/_products.html.erb
<div class="product">
  <strong>Name:</strong>
  <% if display_product_link %>
    <%= link_to products.name, product_path(products) %>
  <% else %>
    <%= products.name %>
  <% end %>
  <p><%= products.description %></p>
</div>

app/views/products/index.html.erb
<h1>Products</h1>

<% @products.each do |product| %>
  <%= render partial: 'products',
             collection: @products,
             locals: { display_product_link: true } %>
<% end %>

app/views/products/show.html.erb
<%= render partial: 'products',
           object: @product,
           locals: { display_product_link: false} %>

<p><%= link_to 'Back', index_path %></p>